# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cursogo
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306